### PR TITLE
Remove test unit dependency and refactor tests for Minitest

### PR DESCRIPTION
**Pull request by summera**
Fixes https://github.com/tomykaira/clockwork/issues/160, https://github.com/tomykaira/clockwork/issues/157, https://github.com/tomykaira/clockwork/issues/161

### CODE REVIEW

**Comment by summera** [comment]
Still working out a few things on this guy to make travis builds pass, but let me know if you are open to this PR. 

Cheers! :beers:

**Comment by robisenberg** [comment]
Hey @summera. Thanks very much for your contribution!

I'm really sorry about the lack of communication and progress recently. I've been snowed under with the day job. I suspect @tomykaira is in a similar position, as I haven't heard from him.

@tomykaira is the main project maintainer, my role has really only been to support the Database-synced Events feature that I added. I was reluctant to go ahead and make these major changes to the tests without @tomykaira's approval.

I'm not really sure how best to proceed. Any ideas?

**Comment by robisenberg** [comment]
By the way, I meant to say that I can see you've but a lot of work into this, so I really do appreciate it.

**Comment by summera** [comment]
@robisenberg No worries! I understand.

Ahh I see. I actually wanted to add some features to the database-synced events and that's what drove me to fix up these tests :smile: . I didn't want to make changes without being able to run all tests haha. Once this is good to go, I'd love to get your thoughts on some ideas I have for the db-synced events if you're open to that?

Hmmm. That's a tough one. I think fixing up these tests as soon as we can is pretty important given the amount of issues and PRs relying on it. It could be holding people back from contributing as well.

**Comment by summera** [comment]
@robisenberg Any word from @tomykaira ?

If not, and you aren't comfortable with merging changes into master, what do you think about merging updates to another branch or fork to keep the progression of this project going?

**Comment by robisenberg** [comment]
Hi @summera - apologies for the not writing sooner. No word from @tomykaira I'm afraid.

I've just emailed @koriroys (someone else listed as a maintainer) and also @adamwiggins (the original author of Clockwork). I've never interacted with either of them before, but I'm hoping maybe they can give some advice/guidance.

I'm going to wait until Friday, but I think we need to make a decision about the future of the Clockwork gem, one way or another. I'm hoping to have some time to dedicate to Clockwork on Friday, so maybe we can either fork the project, or just go ahead and merge into master.

My time is pretty limited, and it seems there's no-one else around to support Clockwork. Would you be interested in being a maintainer and maybe helping out a bit?

**Comment by koriroys** [comment]
I'm A+ on an updated test suite (my contributions to clockwork were all refactoring and cleanup), and pretty sure @tomykaira would be too. Happy to merge this when you're ready.

**Comment by robisenberg** [comment]
@koriroys thanks! ok, sounds good - just didn't want to go ahead completely on my own. But if you think he'd be ok with it I'm happy too.

Thanks again.

**Comment by summera** [comment]
@robisenberg no worries. I know you're busy.

sounds like a plan! I'd be happy to help out as a maintainer :+1:

**Comment by robisenberg** [comment]
Ok, I've checked this out in detail and it looks good. Thanks @summera.

I get a lot of warnings in the output when running the tests (I tried with a few versions, but all > 2):

```
/Users/rob/Dropbox/dev/projects/ruby/gems/clockwork-summera/test/database_events/test_helpers.rb:42: warning: instance variable @name not initialized
/Users/rob/Dropbox/dev/projects/ruby/gems/clockwork-summera/test/database_events/test_helpers.rb:42: warning: instance variable @name not initialized
/Users/rob/Dropbox/dev/projects/ruby/gems/clockwork-summera/test/database_events/test_helpers.rb:42: warning: instance variable @name not initialized
/Users/rob/Dropbox/dev/projects/ruby/gems/clockwork-summera/test/database_events/test_helpers.rb:42: warning: instance variable @name not initialized
/Users/rob/Dropbox/dev/projects/ruby/gems/clockwork-summera/test/database_events/test_helpers.rb:42: warning: instance variable @name not initialised
```

A little digging suggests this is because ruby being called with `-w` (verbose mode) - possibly a changed default in newer MiniTests?

Either way, it's better to go ahead with this merge, and I can fix these warnings with a commit after.

**Comment by summera** [comment]
@robisenberg perfect

This is my output from the tests without any changes. Sounds like I'm getting less warnings than you

```
*** Mocha deprecation warning: Test::Unit or MiniTest must be loaded *before* `require 'mocha/setup'`.


*** Mocha deprecation warning: If you're integrating with a test library other than Test::Unit or MiniTest, you should use `require 'mocha/api'` instead of `require 'mocha/setup'`.

Run options: --seed 39341

# Running:

.....................................................................................

Finished in 0.711304s, 119.4989 runs/s, 213.6922 assertions/s.

85 runs, 152 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by robisenberg** [comment]
Interesting. What version of Ruby are you on?

**Comment by summera** [comment]
I tried with 2.2.2 and 2.3.0

**Comment by robisenberg** [comment]
Ok, maybe it's something in my setup. :)

**Comment by robisenberg** [comment]
I get the errors when I just ran `rake` rather than `bundle exec rake`. I'm happy to leave this as it is then, as `bundler` should be explicitly used to run it really.

**Comment by pr0d1r2** [comment]
@robisenberg what do you think about switching to `rspec`? I have added testing suite for it in https://github.com/pr0d1r2/clockwork/commit/f1ef8811ccd214ddadf82454dadb90f17941ad85 (as this pull request was still WIP and I needed to TDD mentioned change) and I am willing to rewrite whole testing suite to rspec if you agree to switch.

**Pull request merged**
